### ISSUE TITLE
Add as a remote module to ITK

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKTextureFeatures#10]
@jbvimort I was about to bump the latest version of the ITKTextureFeatures when I realized that it has not been added as a remote to ITK yet.

I'm wondering whether it should be added as a remote to ITK, or whether you are waiting for #3 to be tackled.

May be Matt, Beatriz and/or François should may be inquired to be sure?

**Comment by jbvimort** [comment]
Yes, probably @thewtex  and @bpaniagua should be the right persons to ask.

**Comment by bpaniagua** [comment]
Hi @jhlegarreta, that depends on how close @blowekamp is to finish his first order texture statistics. @blowekamp how is that going?

**Comment by blowekamp** [comment]
The filter should be in good shape. I'll work on the pull request tomorrow.

**Comment by thewtex** [comment]
Adding here:

  http://review.source.kitware.com/#/c/22531/

**Comment by jhlegarreta** [comment]
The topic was merged into ITK master as of July, 31st with the commit hash 2fed5dc7e0523e0afac6c3ddf1859e4a7609fff6.
Thanks.
