### ISSUE TITLE
Improve Mask Input for RunLengthTextureFeaturesImageFilter

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITKTextureFeatures#36]
The following are missing best practices:
 - Add MaskImageType definition, and pixel type
 - Use Macros for setting named input
 - Make pipeline input named, number and optional

See 95705f5ee61fdff90612459d66aea2622fb53d6a for similar changes.

**Comment by jbvimort** [comment]
Everything has been solved with  #37 #39 and #41
