### ISSUE TITLE
Review wrapping masked template parameter

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITKTextureFeatures#42]
With the merge of #41, the C++ interface has changed the default for the mask image type. Currently, they Wrapping still specifies the mask image type to be the same as the input images. Should the wrapping be changed?

Also consider wrapping for "VectorImage" as can simplify the usage, by not needing to specify the image vector size as part of the image type.

**Comment by thewtex** [comment]
The wrapping does not currently specify TMaskImage and uses the default type, which seems reasonable.

  https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/blob/c1039d5ab834d8dba77ae4b9a3cc96a60788686b/include/itkFirstOrderTextureFeaturesImageFilter.h#L53-L57

Wrapping is present for VectorImage:

  https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/blob/c1039d5ab834d8dba77ae4b9a3cc96a60788686b/wrapping/itkRunLengthTextureFeaturesImageFilter.wrap#L58-L59
