### ISSUE TITLE
Update ITK remote module

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITKTextureFeatures#47]
The ITK remote module is a bit out of date now pointing to  2fed5dc7e0523e0afac6c3ddf1859e4a7609fff6.

**Comment by blowekamp** [comment]
The the repo is a good state for ITK to now reference?

**Comment by blowekamp** [comment]
Made pull request:
http://review.source.kitware.com/#/c/22740/

**Comment by jbvimort** [comment]
I'm actually working on making the filters work for input image of floating type, maybe we could wait a couple of days?

**Comment by blowekamp** [comment]
Do you anticipate and change to the API?

Getting ITK updated this week would be good, so I can move a couple thing forward. I'm not sure if there is much harm with extra update to the ITK remote module reference though.

**Comment by jbvimort** [comment]
There will be no change in the API, the pull request has just been created (see #48 )

**Comment by blowekamp** [comment]
Updated Gerrit patch with current master:
http://review.source.kitware.com/#/c/22740/
