### ISSUE TITLE
nan values in output

### ISSUE THREAD

**Issue by maekclena** [InsightSoftwareConsortium/ITKTextureFeatures#68]
For some inputs, `nan` values can appear in the output. From the few tests I did, it seems to happen with floating values and isolated points in the mask.

Minimal example:
```C++
#include "itkImage.h"
#include "itkVectorImage.h"
#include "itkCoocurrenceTextureFeaturesImageFilter.h"

typedef itk::Image<float, 2> ImageType;
typedef itk::Image<unsigned char, 2> MaskType;
typedef itk::VectorImage<float, 2> VectorType;
typedef itk::Statistics::CoocurrenceTextureFeaturesImageFilter<ImageType, VectorType> TextureType;

template<typename TImage>
typename TImage::Pointer createImage()
{
	typename TImage::Pointer image = TImage::New();
	typename TImage::RegionType region;
	region.SetIndex({{0, 0}});
	region.SetSize({{5, 5}});
	image->SetRegions(region);
	image->Allocate(true);
	return image;
}

int main()
{
	ImageType::Pointer image = createImage<ImageType>();
	MaskType::Pointer mask = createImage<MaskType>();
	mask->SetPixel({{2, 2}}, 1);
	TextureType::Pointer texture = TextureType::New();
	texture->SetInput(image);
	texture->SetMaskImage(mask);
	texture->Update();
	
	std::cout << texture->GetOutput()->GetPixel({{2, 2}}) << std::endl;
}
```

Output:
```
[nan, 0, nan, nan, nan, nan, nan, nan]
```

**Comment by phcerdan** [comment]
I can reproduce this... I guess a non-documented precondition is that the mask has to have more than one value?

The nans disappear if you add another pixel with value 1 to the mask (or don't use the mask)

**Comment by maekclena** [comment]
What happens is that, on line [325](https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/blob/5dbe57d072c5452d8ba86703b459bf7e13fa6673/include/itkCoocurrenceTextureFeaturesImageFilter.hxx#L325), the variable `totalNumberOfFreq` is zero. Which makes sense since the frequency of coocurrences in a window of one pixel is undefined.

**Comment by phcerdan** [comment]
Thanks @maekclena! Feel free to open a PR introducing a check for that precondition: `assert(totalNumberOfFreq != 0)` or similar.
