### ISSUE TITLE
Wrong output with signed pixel value

### ISSUE THREAD

**Issue by maekclena** [InsightSoftwareConsortium/ITKTextureFeatures#71]
When using an image with signed pixel type as input, the output is wrong.
Minimal example:
```c++
#include "itkImage.h"
#include "itkVectorImage.h"
#include "itkCoocurrenceTextureFeaturesImageFilter.h"

template<typename TImage>
void run()
{
	typename TImage::Pointer image = TImage::New();
	typename TImage::RegionType region;
	region.SetIndex({{0, 0}});
	region.SetSize({{5, 5}});
	image->SetRegions(region);
	image->Allocate(true);
	
	using TextureType = itk::Statistics::CoocurrenceTextureFeaturesImageFilter<TImage, itk::VectorImage<float, 2>>;
	typename TextureType::Pointer texture = TextureType::New();
	texture->SetInput(image);
	texture->Update();
	
	std::cout << texture->GetOutput()->GetPixel({{2, 2}}) << std::endl;;
}

int main()
{
	run<itk::Image<signed int, 2>>();
	run<itk::Image<unsigned int, 2>>();
}
```

Output:
```
[0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 0, -0.00392157]
```

The problem comes from the `DigitizerFunctor`, on line [80](https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/blob/5dbe57d072c5452d8ba86703b459bf7e13fa6673/include/itkDigitizerFunctor.h#L80) the computing of the output range overflows.

**Comment by thewtex** [comment]
@maekclena good catch! :eagle: :eye: Thanks for the nice report.

You you please open a pull request to compute the output range with `double` to avoid overflow and add your test code to the test suite?

**Comment by maekclena** [comment]
I've been trying to fix this issue but unfortunately changing the output range to `double` is not enough. I assumed the `DigitizerFunctor` applied a rescaling but the formula is slightly different and returns different results between signed and unsigned types.

So if anybody has more insight on why it was written like this, I'm listening.

**Comment by phcerdan** [comment]
Yeah, thanks @maekclena!

The overflow is there...
```cpp
m_Min(NumericTraits<PixelType>::min()),
m_Max(NumericTraits<PixelType>::max()){}

...
 return Math::Floor< TOutput >((inputPixel - m_Min)/((m_Max-m_Min)/ (float)m_NumberOfBinsPerAxis));
```

In both: `inputPixel - m_Min` and `m_Max-m_Min`

**Comment by maekclena** [comment]
@phcerdan even after resolving the overflows I think the formula is missing a shift term to be able to deal with signed types. But If I add it then the tests fail.

**Comment by phcerdan** [comment]
>  But If I add it then the tests fail.

That might not be a bad thing. Maybe it is a regression test not checking correctness but "stability". Could you open a PR with your ongoing progress on this?

**Comment by maekclena** [comment]
After more digging, here's my conclusion. The formula is correct, the problem comes from the default values for `m_Min` and `m_Max` which are set to the type's minimum and maximum. For the filter to be consistent across all types they should be defaulted to the image's minimum and maximum.

While this shouldn't invalidate any test (which all specify their own min/max), it does mean different results with the default settings.

Also, `ScalarImageToCooccurrenceMatrixFilter` seems to do the same so any change should be propagated there.

**Comment by phcerdan** [comment]
Thanks for the digging @maekclena. That makes sense, we can set min and max in the constructor of the Digitizer. We can not change the default of min and max, because we don't know better at compile time. We could add a requirement that HistogramMinimum and Maximum have to be provided by the user of the texture filter. And we should check for overflow on those.

A nice improvement to the digitizer could be:
- A check (or assert) for overflow based on HistogramMinimum and HistogramMaximum.
- Helper function to set and compute HistogramMinimum and Max from a reference image.
- Helper function to set and compute sensible number of bins from a reference image. 

```
using TextureType = itk::Statistics::CoocurrenceTextureFeaturesImageFilter<TImage, itk::VectorImage<float, 2>>;
typename TextureType::Pointer texture = TextureType::New();
texture->SetInput(image);
texture->SetHistogramMaximum(maxHistoValue);
texture->SetHistogramMinimum(minHistoValue);
texture->Update();
```

max and min values in the image (or in a range of images) can be dynamically computed with:
```
std::vector<PixelType> imageMins(numberOfInputImages);
std::vector<PixelType> imageMaxs(numberOfInputImages);
for (size_t i = 0; i < numberOfInputImages; ++i){
    using MinMaxFilter = itk::MinimumMaximumImageFilter<TInputImageType>;
    auto minmax = MinMaxFilter::New();
    minmax->SetInput(images[i]);
    minmax->Update();
    imageMins[i] = minmax->GetMinimum();
    imageMaxs[i] = minmax->GetMaximum();
}
PixelType maxHistoValue = std::max_element(imageMaxs.begin(), imageMaxs.end());
PyxelType minHistoValue = std::min_element(imageMins.begin(), imageMins.end());
```

Would you be able to provide a function for that overflow checking?
